### ISSUE TITLE
Token for Capturista

### ISSUE THREAD

**Issue by csssaz** [erikiado/jp2_online#26]
## Context

#21 introduced a signal to create tokens for users. It's currently creating Tokens for all kinds of users, but it should only do so for Capturistas.

The code is inside perfiles_usuario/models.py

## Expected result

I guess we should only be creating tokens for Capturistas, and not for any kind of user.

## Possible Fix

The fix is trivial, just changing the sender of the signal. But maybe we want other users to have tokens to? I'm pretty sure the answer is no, but any further comments are appreciated.

This template was adapted ~stolen~ from [Aurelia Moser](https://bl.ocks.org/auremoser/72803ba969d0e61ff070)

**Comment by erikiado** [comment]
Yes, this should be fixed. The only user able to login to offline app will be the Capturista

**Comment by AndreeToledo** [comment]
Not only the capturista, thelma as an administrator should be able to use the app offline too.

This change should also include that when an admin user is created, everything necessary to make her a capturista is added automatically.

**Comment by fernandolobato** [comment]
Resolved with PR #28
