### ISSUE TITLE
Gender attribute missing from Integrante

### ISSUE THREAD

**Issue by Ral15** [erikiado/jp2_online#45]
In Familia models.py, Integrante has no attribute gender.

## Context

Gender attribute is required in the 'estudio socioeconomico' for each member of a Family.

## Process

Add gender attribute to Integrante at familias/models.py

## Expected result

The Integrante from a Familia will have the gender attribute.

This template was adapted ~stolen~ from [Aurelia Moser](https://bl.ocks.org/auremoser/72803ba969d0e61ff070)

**Comment by fernandolobato** [comment]
https://cdn.psychologytoday.com/sites/default/files/styles/article-inline-half/public/field_blog_entry_images/Gender2_0.png?itok=hIsLsu3n

**Comment by AndreeToledo** [comment]
Will be added within the next 3 pull requests.

**Comment by AndreeToledo** [comment]
Gender is not an attribute required of the integrantes of a familia, we use their rol in the family, for that reason I am closing this pull request.
