### ISSUE TITLE
Redirection when clicking San Juan Pablo

### ISSUE THREAD

**Issue by AndreeToledo** [erikiado/jp2_online#60]
## Context
Currently clicking the San Juan Pablo Button, on the navbar while being logged in, does not take you to your homepage when clicking it, it takes you to the loign page, but you are already logged in.

## Process

1. User logs in
2. User is redirected to his homepage
3. User clicks the San Juan Pablo button on the navbar
4. User is redirected to the login page.

## Expected result

The user should be redirected to his homepage, according to his role

## Current result

The user is redirected to the login page.

## Possible Fix

Change the destination of this page according to the user that is logged in.
As a failsave the login view, should check wether the user is logged in, and if it is, it should be redirected to his homepage.

This template was adapted ~stolen~ from [Aurelia Moser](https://bl.ocks.org/auremoser/72803ba969d0e61ff070)

**Comment by csssaz** [comment]
fix in #65
