### ISSUE TITLE
No 500 and 404 default pages.

### ISSUE THREAD

**Issue by AndreeToledo** [erikiado/jp2_online#62]
## Context

As we prepare to show the website to thelma, we need to create pages for error codes 404 and 500, in order to prevent her from getting just a white page with the status number.

This template was adapted ~stolen~ from [Aurelia Moser](https://bl.ocks.org/auremoser/72803ba969d0e61ff070)

**Comment by fernandolobato** [comment]
Solved in #68  and #66
